CREATE TABLE IF NOT EXISTS "USUARIO" (
  "ID_USUARIO" TEXT PRIMARY KEY NOT NULL,
  "NOME" TEXT NOT NULL,
  "EMAIL" TEXT NOT NULL UNIQUE,
  "EMAIL_VERIFICADO" BOOLEAN NOT NULL DEFAULT FALSE,
  "IMAGEM" TEXT,
  "CRIADO_EM" TIMESTAMP NOT NULL DEFAULT NOW(),
  "ATUALIZADO_EM" TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "SESSAO" (
  "ID_SESSAO" TEXT PRIMARY KEY NOT NULL,
  "EXPIRA_EM" TIMESTAMP NOT NULL,
  "TOKEN" TEXT NOT NULL UNIQUE,
  "CRIADO_EM" TIMESTAMP NOT NULL,
  "ATUALIZADO_EM" TIMESTAMP NOT NULL,
  "ENDERECO_IP" TEXT,
  "AGENTE_USUARIO" TEXT,
  "ID_USUARIO" TEXT NOT NULL,
  "REVOGADA" BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS "CONTA" (
  "ID_CONTA" TEXT PRIMARY KEY NOT NULL,
  "ID_CONTA_PROVEDOR" TEXT NOT NULL,
  "ID_PROVEDOR" TEXT NOT NULL,
  "ID_USUARIO" TEXT NOT NULL,
  "TOKEN_ACESSO" TEXT,
  "TOKEN_ATUALIZACAO" TEXT,
  "TOKEN_ID" TEXT,
  "TOKEN_ACESSO_EXPIRA_EM" TIMESTAMP,
  "TOKEN_ATUALIZACAO_EXPIRA_EM" TIMESTAMP,
  "ESCOPO" TEXT,
  "SENHA" TEXT,
  "CRIADO_EM" TIMESTAMP NOT NULL,
  "ATUALIZADO_EM" TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS "VERIFICACAO" (
  "ID_VERIFICACAO" TEXT PRIMARY KEY NOT NULL,
  "IDENTIFICADOR" TEXT NOT NULL,
  "VALOR" TEXT NOT NULL,
  "EXPIRA_EM" TIMESTAMP NOT NULL,
  "CRIADO_EM" TIMESTAMP,
  "ATUALIZADO_EM" TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "PESQUISAS" (
  "ID_PESQUISA" TEXT PRIMARY KEY NOT NULL,
  "ID_USUARIO" TEXT NOT NULL,
  "CONSULTA" TEXT NOT NULL,
  "REGIAO" TEXT,
  "STATUS" TEXT NOT NULL DEFAULT 'completed',
  "CRIADO_EM" TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "EMPRESAS" (
  "ID_EMPRESA" TEXT PRIMARY KEY NOT NULL,
  "ID_USUARIO" TEXT NOT NULL,
  "ID_PESQUISA" TEXT,
  "NOME" TEXT NOT NULL,
  "CATEGORIA" TEXT,
  "CIDADE" TEXT,
  "ESTADO" TEXT,
  "ENDERECO" TEXT,
  "TELEFONE" TEXT,
  "EMAIL" TEXT,
  "SITE" TEXT,
  "DESCRICAO" TEXT,
  "DADOS_BRUTOS" JSONB,
  "CRIADO_EM" TIMESTAMP NOT NULL DEFAULT NOW(),
  "ATUALIZADO_EM" TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "PROPOSTAS" (
  "ID_PROPOSTA" TEXT PRIMARY KEY NOT NULL,
  "ID_USUARIO" TEXT NOT NULL,
  "ID_EMPRESA" TEXT NOT NULL,
  "TITULO" TEXT NOT NULL,
  "STATUS" TEXT NOT NULL DEFAULT 'draft',
  "RESUMO" TEXT,
  "ESCOPO" JSONB,
  "VALIDO_ATE" TIMESTAMP,
  "CRIADO_EM" TIMESTAMP NOT NULL DEFAULT NOW(),
  "ATUALIZADO_EM" TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "VERSOES_PROPOSTA" (
  "ID_VERSAO_PROPOSTA" TEXT PRIMARY KEY NOT NULL,
  "ID_USUARIO" TEXT NOT NULL,
  "ID_PROPOSTA" TEXT NOT NULL,
  "VERSAO" INTEGER NOT NULL DEFAULT 1,
  "CONTEUDO" JSONB NOT NULL,
  "CRIADO_EM" TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "NOTAS_EMPRESA" (
  "ID_NOTA_EMPRESA" TEXT PRIMARY KEY NOT NULL,
  "ID_USUARIO" TEXT NOT NULL,
  "ID_EMPRESA" TEXT NOT NULL,
  "CONTEUDO" TEXT NOT NULL,
  "CRIADO_EM" TIMESTAMP NOT NULL DEFAULT NOW(),
  "ATUALIZADO_EM" TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS "SESSAO_ID_USUARIO_IDX" ON "SESSAO" ("ID_USUARIO");
CREATE INDEX IF NOT EXISTS "CONTA_ID_USUARIO_IDX" ON "CONTA" ("ID_USUARIO");
CREATE INDEX IF NOT EXISTS "PESQUISAS_ID_USUARIO_IDX" ON "PESQUISAS" ("ID_USUARIO");
CREATE INDEX IF NOT EXISTS "EMPRESAS_ID_USUARIO_IDX" ON "EMPRESAS" ("ID_USUARIO");
CREATE INDEX IF NOT EXISTS "PROPOSTAS_ID_USUARIO_IDX" ON "PROPOSTAS" ("ID_USUARIO");
CREATE INDEX IF NOT EXISTS "NOTAS_EMPRESA_ID_USUARIO_IDX" ON "NOTAS_EMPRESA" ("ID_USUARIO");

ALTER TABLE "SESSAO" ADD CONSTRAINT "SESSAO_USUARIO_FK" FOREIGN KEY ("ID_USUARIO") REFERENCES "USUARIO"("ID_USUARIO") ON DELETE CASCADE;
ALTER TABLE "CONTA" ADD CONSTRAINT "CONTA_USUARIO_FK" FOREIGN KEY ("ID_USUARIO") REFERENCES "USUARIO"("ID_USUARIO") ON DELETE CASCADE;
ALTER TABLE "PESQUISAS" ADD CONSTRAINT "PESQUISAS_USUARIO_FK" FOREIGN KEY ("ID_USUARIO") REFERENCES "USUARIO"("ID_USUARIO") ON DELETE CASCADE;
ALTER TABLE "EMPRESAS" ADD CONSTRAINT "EMPRESAS_PESQUISA_FK" FOREIGN KEY ("ID_PESQUISA") REFERENCES "PESQUISAS"("ID_PESQUISA") ON DELETE SET NULL;
ALTER TABLE "EMPRESAS" ADD CONSTRAINT "EMPRESAS_USUARIO_FK" FOREIGN KEY ("ID_USUARIO") REFERENCES "USUARIO"("ID_USUARIO") ON DELETE CASCADE;
ALTER TABLE "PROPOSTAS" ADD CONSTRAINT "PROPOSTAS_EMPRESA_FK" FOREIGN KEY ("ID_EMPRESA") REFERENCES "EMPRESAS"("ID_EMPRESA") ON DELETE CASCADE;
ALTER TABLE "PROPOSTAS" ADD CONSTRAINT "PROPOSTAS_USUARIO_FK" FOREIGN KEY ("ID_USUARIO") REFERENCES "USUARIO"("ID_USUARIO") ON DELETE CASCADE;
ALTER TABLE "VERSOES_PROPOSTA" ADD CONSTRAINT "VERSOES_PROPOSTA_PROPOSTA_FK" FOREIGN KEY ("ID_PROPOSTA") REFERENCES "PROPOSTAS"("ID_PROPOSTA") ON DELETE CASCADE;
ALTER TABLE "NOTAS_EMPRESA" ADD CONSTRAINT "NOTAS_EMPRESA_EMPRESA_FK" FOREIGN KEY ("ID_EMPRESA") REFERENCES "EMPRESAS"("ID_EMPRESA") ON DELETE CASCADE;
ALTER TABLE "NOTAS_EMPRESA" ADD CONSTRAINT "NOTAS_EMPRESA_USUARIO_FK" FOREIGN KEY ("ID_USUARIO") REFERENCES "USUARIO"("ID_USUARIO") ON DELETE CASCADE;
